name: Build and deploy Python project to Azure Function App - devsecops-azf-python-api

on:
  push:
    branches:
      - main      

  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.12' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  cicd:    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build
        run: pip install -r requirements.txt    

      - name: SAST
        uses: Bom-Dia-Codigo/devsecops-horusec-action@v0.3.0
        with:
          path: ./
          arguments: --custom-rules-path=horusec-config.json #--log-level=debug 

      - name: SCA
        uses: snyk/actions/python-3.12@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args:
            --skip-unresolved=true  
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'devsecops-azf-python-api'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          remote-build: true
                    