name: Build and deploy Python project to Azure Function App - devsecops-azf-python-api

on:
  push:
    branches:
      - main      

  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.12' 

jobs:
  sast:    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Run Horusec
        uses: Bom-Dia-Codigo/devsecops-horusec-action@v0.3.0
        with:
          path: ./
          arguments: --log-level=debug --custom-rules-path=horusec-config.json
  deploy:    
    runs-on: ubuntu-latest    
    permissions:
      contents: read
      id-token: write
    needs: sast
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies (optional)
        run: pip install -r requirements.txt    
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'devsecops-azf-python-api'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          remote-build: true
                    